### ISSUE TITLE
Unable to locate the filepath provided in Line #297,321

### ISSUE THREAD

**Issue by himajakethiri** [ssreddy2020/MSCS721-roomScheduler#1]
When i tried to import or export room details it is showing the FileNotFound Exception.I think these suggestions will be helpful for you.

Instead of using absolute path   D:\JavaWorkSpace\result.json it is better to use methods like below.
String filename=” “;
a.filename. getAbsolutePath(); or b. filename.Contains(“.json”)

**Comment by ssreddy2020** [comment]
Fixed the issue.

Changed the file path from absolute to relative (Included .json file in project folder)

Thanks,
Sandeep
