### ISSUE TITLE
Adding the same room too many times

### ISSUE THREAD

**Issue by himajakethiri** [ssreddy2020/MSCS721-roomScheduler#2]
When I tried to add the room with same name for more than one time it is accepting. Try to fix this issue.
Solution:
1.write a condition to check whether room already added or not.and try to print “room already exists”.

**Comment by ssreddy2020** [comment]
Status: Fixed

In add method included the condition to check whether the room already exists or not. If it exists, room is not added to the list. If it does not exist then the room gets added to the list.

Thanks,
Sandeep
