### ISSUE TITLE
Accepting alphanumerical and special characters for room name and date etc.

### ISSUE THREAD

**Issue by himajakethiri** [ssreddy2020/MSCS721-roomScheduler#3]
In scheduleRoom() method there is no validation for some fields like room name,date and time etc.If you enter anything like numbers and alphabets it is accepting .It may be better if you to add validations.

**Comment by ssreddy2020** [comment]
Status: Fixed

Included date validation method to check whether the start date and end date are in a specific format.  Included pattern matches to check whether the room name contains only alphabets.

Thanks,
Sandeep
